# ----------------------------------------------------------------------
# JupyterLab Notebook for analyzing E3SM-ELM land model output
# with Google Earth Engine and GEEmap
# ----------------------------------------------------------------------

FROM jupyter/scipy-notebook:lab-3.3.2
LABEL maintainer.name="Shawn P. Serbin" \
      maintainer.email="sserbin@bnl.gov" \
      author.name="Shawn P. Serbin" \
      author.email="sserbin@bnl.gov" \
      description="Jupyter-SciPy Container"

ENV TOOLS_REPOSITORY_RAW_URL=https://raw.githubusercontent.com/FASSt-simulation/fasst_simulation_tools

# install Python packages you often use
RUN set -ex \
   && conda install --quiet --yes \
   # choose the Python packages you need
   'matplotlib' \
   'plotly' \
   'folium' \
   'dask' \
   'pandas' \
   'xarray' \
   'geopandas' \
   'ipyleaflet' \
   && conda clean --all -f -y \
   && conda install --quiet --yes -c conda-forge \
   'nc-time-axis' \
   'netCDF4' \
   && conda clean --all -f -y \
   && mamba install --quiet --yes -c conda-forge \
   'earthengine-api' \
   'geemap' \
   'pygis' \
   && mamba clean --all -f -y \
   && rm -rf "/home/${NB_USER}/.cache/yarn" \
   && rm -rf "/home/${NB_USER}/.node-gyp" \
   && fix-permissions "${CONDA_DIR}" \
   && fix-permissions "/home/${NB_USER}"

# Make local directories to use with plotting of ELM output
RUN mkdir "/home/${NB_USER}/scripts" \
   && mkdir "/home/${NB_USER}/inputdata" \
   && mkdir "/home/${NB_USER}/output" \
   && fix-permissions "/home/${NB_USER}/scripts" \
   && fix-permissions "/home/${NB_USER}/inputdata" \
   && fix-permissions "/home/${NB_USER}/output" \
   && fix-permissions "/home/${NB_USER}"

# Setup default user, when enter docker container
USER ${NB_UID}
WORKDIR "${HOME}"

# EOF