
# ----------------------------------------------------------------------
# JupyterLab Notebook for analyzing E3SM-ELM land model output
#
# This adds the example NGEE-Arctic notebook scripts to the base container
# ----------------------------------------------------------------------

# grab the jupyter-lab container
FROM fasstsimulation/fasst_simulation_tools:fasst_jupyterlab_3.3.2_gee
LABEL maintainer.name="Shawn P. Serbin" \
      maintainer.email="sserbin@bnl.gov" \
      author.name="Shawn P. Serbin" \
      author.email="sserbin@bnl.gov" \
      description="ELM Analysis Jupyter-Lab Container"

ENV TOOLS_REPOSITORY_RAW_URL=https://raw.githubusercontent.com/FASSt-simulation/fasst_simulation_tools

# Copy in example plotting scripts for use with model output
# add Ben Sulman's matplotlib plotting ascetics defaults
RUN cd "/home/${NB_USER}/scripts" \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/elm_scripts/plotting/plot_KG64_ELM_output.py \
   && chmod 775 plot_KG64_ELM_output.py \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/elm_scripts/plotting/plot_ELM_output.py \
   && chmod 775 plot_ELM_output.py \
   && cd "/home/${NB_USER}" \
   && mkdir -p "/home/${NB_USER}/.config/matplotlib" \
   && cd "/home/${NB_USER}/.config/matplotlib" \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/elm_scripts/plotting/matplotlibrc \
   && cd "/home/${NB_USER}" \
   && fix-permissions "/home/${NB_USER}"

# Add example jupyter notebook scripts here
RUN cd "/home/${NB_USER}/scripts" \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_variable.ipynb \
   && chmod 775 plot_ELM_variable.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_variable_2D.ipynb \
   && chmod 775 plot_ELM_variable_2D.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_output.ipynb \
   && chmod 775 plot_ELM_output.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_radiation.ipynb \
   && chmod 775 plot_ELM_radiation.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_moisture_temperature.ipynb \
   && chmod 775 plot_moisture_temperature.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_soil_BGC.ipynb \
   && chmod 775 plot_soil_BGC.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_veg_data.ipynb \
   && chmod 775 plot_veg_data.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_ensembles.ipynb \
   && chmod 775 plot_ELM_ensembles.ipynb \
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_compare_cases.ipynb \
   && chmod 775 plot_ELM_compare_cases.ipynb \
   # GEE notebooks
   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/plot_ELM_vs_GEE_data.ipynb \
   && chmod 775 plot_ELM_vs_GEE_data.ipynb

# add back in if we want examples showing how to run the model from within a notebook
#   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/run_ELM_KG64_basic.ipynb \
#   && chmod 775 run_ELM_KG64_basic.ipynb \
#   && wget $TOOLS_REPOSITORY_RAW_URL/main/notebooks/ngeearctic/run_plot_KG64_ELM_output.ipynb \
#   && chmod 775 run_plot_KG64_ELM_output.ipynb

# Setup default user, when enter docker container
USER ${NB_UID}
WORKDIR "${HOME}"

# EOF